# Create the App Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  namespace: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
    # Specify the container
      containers:
        - name: helloworld
          image: prengineer/2bcloud:latest
          env:
            # Specify the Time Zone
            - name: TZ
              value: America/New_York
          resources:
            limits:
              memory: "500Mi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 80